let elegir=document.getElementById("selectGrafico")
console.log(elegir)
let flecha=document.getElementById("flecha")
console.log(flecha)
flecha.addEventListener("click",window.scrollTo(0, 1500)/*elegir.scrollIntoView({behavior:"smooth"})*/)
